# Generated by Django 2.2.6 on 2019-11-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('truck_id', models.TextField(blank=True, null=True)),
                ('evento', models.TextField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'macro',
                'managed': False,
            },
        ),
    ]
